using System.Text;
using Content.Client.UserInterface.Controls;
using Content.Client._Harvest.Botany;
using Content.Shared._Harvest.Botany.PlantHealthAnalyzer;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._Harvest.Botany.PlantHealthAnalyzer;

[GenerateTypedNameReferences]
public sealed partial class PlantHealthAnalyzerWindow : FancyWindow
{
    private static readonly Color GoodColor = BotanyAnalyzerUiHelpers.Good;
    private static readonly Color WarningColor = BotanyAnalyzerUiHelpers.Warning;
    private static readonly Color BadColor = BotanyAnalyzerUiHelpers.Bad;
    private static readonly Color NeutralColor = BotanyAnalyzerUiHelpers.Neutral;

    private float _healthTarget;
    private float _growthTarget;
    private float _toxinsTarget;
    private float _pestsTarget;
    private float _weedsTarget;

    public PlantHealthAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(PlantHealthAnalyzerUiState state, EntityUid? plantHolder)
    {
        var plant = state.Plant;
        EmptyLabel.Visible = plant == null;
        PlantScroll.Visible = plant != null;

        if (plant == null)
        {
            PlantSprite.SetEntity(null);
            return;
        }

        PlantSprite.SetEntity(plantHolder);
        PlantNameLabel.Text = Loc.GetString(plant.PlantName);
        _healthTarget = plant.HealthPercent;
        _growthTarget = plant.GrowthPercent;
        _toxinsTarget = Math.Clamp(GetTolerancePercent(plant.ToxinLevel, plant.ToxinTolerance), 0f, 100f);
        _pestsTarget = Math.Clamp(GetTolerancePercent(plant.PestLevel, plant.PestTolerance), 0f, 100f);
        _weedsTarget = Math.Clamp(GetTolerancePercent(plant.WeedLevel, plant.WeedTolerance), 0f, 100f);

        SetHealthBar(plant);
        SetProgressBar(GrowthBar, GrowthBarLabel,
            $"{Loc.GetString("plant-health-analyzer-label-growth")}  •  {plant.GrowthPercent:0.#}%",
            plant.GrowthPercent >= 100f ? GoodColor : NeutralColor);
        AgeLabel.SetMessage(Loc.GetString("seed-analyzer-cycles", ("value", plant.Age)), NeutralColor);
        HarvestLabel.SetMessage(Loc.GetString(plant.ReadyToHarvest
                ? "plant-health-analyzer-ready"
                : "plant-health-analyzer-not-ready"),
            plant.ReadyToHarvest ? GoodColor : NeutralColor);

        SetToleranceBar(ToxinsBar, ToxinsBarLabel, "plant-health-analyzer-label-toxins", plant.ToxinLevel, plant.ToxinTolerance);
        SetToleranceBar(PestsBar, PestsBarLabel, "plant-health-analyzer-label-pests", plant.PestLevel, plant.PestTolerance);
        SetToleranceBar(WeedsBar, WeedsBarLabel, "plant-health-analyzer-label-weeds", plant.WeedLevel, plant.WeedTolerance);
        ProblemsLabel.SetMessage(FormatDiagnostics(plant.Diagnostics),
            GetDiagnosticColor(plant.Diagnostics));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        var amount = Math.Clamp(args.DeltaSeconds * 6f, 0f, 1f);
        HealthBar.Value = MathHelper.Lerp(HealthBar.Value, _healthTarget, amount);
        GrowthBar.Value = MathHelper.Lerp(GrowthBar.Value, _growthTarget, amount);
        ToxinsBar.Value = MathHelper.Lerp(ToxinsBar.Value, _toxinsTarget, amount);
        PestsBar.Value = MathHelper.Lerp(PestsBar.Value, _pestsTarget, amount);
        WeedsBar.Value = MathHelper.Lerp(WeedsBar.Value, _weedsTarget, amount);
    }

    private void SetHealthBar(PlantHealthAnalyzerData plant)
    {
        var (status, color) = plant.Dead
            ? ("plant-health-analyzer-status-dead", BadColor)
            : plant.Diagnostics.Exists(diagnostic => diagnostic.Severity == PlantDiagnosticSeverity.Critical)
                ? ("plant-health-analyzer-status-critical", BadColor)
                : plant.Diagnostics.Count != 0
                    ? ("plant-health-analyzer-status-attention", WarningColor)
                    : ("plant-health-analyzer-status-healthy", GoodColor);

        HealthBarLabel.Text = $"{Loc.GetString(status)}  •  {plant.HealthPercent:0.#}%";
        SetBarColor(HealthBar, color);
    }

    private static void SetToleranceBar(ProgressBar bar, Label label, string nameKey, float value, float tolerance)
    {
        var percent = GetTolerancePercent(value, tolerance);
        var color = percent >= 100f
            ? BadColor
            : percent >= 75f ? WarningColor : GoodColor;
        SetProgressBar(bar, label,
            $"{Loc.GetString(nameKey)}  •  {Loc.GetString("plant-health-analyzer-tolerance-percent",
                ("current", value.ToString("0.#")),
                ("limit", tolerance.ToString("0.#")),
                ("percent", percent.ToString("0.#")))}",
            color);
    }

    private static float GetTolerancePercent(float value, float tolerance)
    {
        if (tolerance <= 0f)
            return value <= 0f ? 0f : 100f;
        return Math.Max(value / tolerance * 100f, 0f);
    }

    private static void SetProgressBar(ProgressBar bar, Label label, string text, Color color)
    {
        label.Text = text;
        SetBarColor(bar, color);
    }

    private static void SetBarColor(ProgressBar bar, Color color)
    {
        bar.ForegroundStyleBoxOverride ??= new StyleBoxFlat();
        ((StyleBoxFlat) bar.ForegroundStyleBoxOverride).BackgroundColor = color;
    }

    private string FormatDiagnostics(List<PlantDiagnosticData> diagnostics)
    {
        if (diagnostics.Count == 0)
            return Loc.GetString("plant-health-analyzer-diagnostic-none");

        var result = new StringBuilder();
        foreach (var diagnostic in diagnostics)
        {
            if (result.Length > 0)
                result.AppendLine();
            result.Append("• ").Append(GetDiagnosticText(diagnostic));
        }

        return result.ToString();
    }

    private string GetDiagnosticText(PlantDiagnosticData diagnostic)
    {
        var suffix = diagnostic.Type switch
        {
            PlantDiagnosticType.Dead => "dead",
            PlantDiagnosticType.CriticalHealth => "critical-health",
            PlantDiagnosticType.LowHealth => "low-health",
            PlantDiagnosticType.ExcessToxins => "toxins",
            PlantDiagnosticType.ExcessPests => "pests",
            PlantDiagnosticType.ExcessWeeds => "weeds",
            PlantDiagnosticType.OldAge => "old-age",
            _ => "unknown"
        };

        return Loc.GetString($"plant-health-analyzer-diagnostic-{suffix}");
    }

    private static Color GetDiagnosticColor(List<PlantDiagnosticData> diagnostics)
    {
        if (diagnostics.Exists(diagnostic => diagnostic.Severity == PlantDiagnosticSeverity.Critical))
            return BadColor;
        return diagnostics.Count == 0 ? GoodColor : WarningColor;
    }
}
