# gloves
- type: entity
  parent: BaseAction
  id: ActionToggleKnuckleDustersStun
  name: (Dés)activer les coups-de-poing étourdissants
  description: Active/Désactive la matraque étourdissante intégrée aux coups-de-poing.
  components:
  - type: InstantAction
    event: !type:ToggleActionEvent
