using Content.Client.UserInterface.Controls;
using Content.Client._Harvest.Botany;
using Content.Shared._Harvest.Botany.SeedAnalyzer;
using Content.Shared.Atmos.Prototypes;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Harvest.Botany.SeedAnalyzer;

[GenerateTypedNameReferences]
public sealed partial class SeedAnalyzerWindow : FancyWindow
{
    private static readonly Color GoodColor = BotanyAnalyzerUiHelpers.Good;
    private static readonly Color NeutralColor = BotanyAnalyzerUiHelpers.Neutral;

    private readonly IPrototypeManager _prototypes;
    private readonly IGameTiming _timing;
    private bool _hasSeed;
    private TimeSpan _printReadyAt;

    public event Action? OnEjectPressed;
    public event Action? OnPrintPressed;

    public SeedAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        _prototypes = IoCManager.Resolve<IPrototypeManager>();
        _timing = IoCManager.Resolve<IGameTiming>();

        Tabs.SetTabTitle(0, Loc.GetString("seed-analyzer-tab-overview"));
        Tabs.SetTabTitle(1, Loc.GetString("seed-analyzer-tab-production"));

        EjectButton.OnPressed += _ => OnEjectPressed?.Invoke();
        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke();
    }

    public void UpdateState(SeedAnalyzerUiState state, EntityUid? seedEntity)
    {
        var seed = state.Seed;
        _hasSeed = seed != null;
        _printReadyAt = state.PrintReadyAt;
        EmptyLabel.Visible = seed == null;
        DetailsContainer.Visible = seed != null;
        EjectButton.Disabled = seedEntity == null;
        UpdatePrintButton();

        if (seed == null)
        {
            SeedSprite.SetEntity(null);
            return;
        }

        SeedSprite.SetEntity(seedEntity);
        SeedNameLabel.Text = Loc.GetString(seed.DisplayName);
        SeedStatusLabel.Text = Loc.GetString(seed.Viable ? "seed-analyzer-status-viable" : "seed-analyzer-status-unviable");
        SeedStatusLabel.FontColorOverride = NeutralColor;

        SetComparedValue(YieldLabel, seed.Yield.ToString(), seed.Yield, seed.Baseline?.Yield);
        SetComparedValue(PotencyLabel, seed.Potency.ToString("0.##"), seed.Potency, seed.Baseline?.Potency);
        SetComparedValue(EnduranceLabel, seed.Endurance.ToString("0.##"), seed.Endurance, seed.Baseline?.Endurance);
        SetComparedValue(MaturationLabel, FormatCycles(seed.Maturation), seed.Maturation, seed.Baseline?.Maturation,
            seed.Baseline == null ? null : FormatCycles(seed.Baseline.Maturation));
        SetComparedValue(ProductionLabel, FormatCycles(seed.Production), seed.Production, seed.Baseline?.Production,
            seed.Baseline == null ? null : FormatCycles(seed.Baseline.Production));
        SetComparedValue(LifespanLabel, FormatCycles(seed.Lifespan), seed.Lifespan, seed.Baseline?.Lifespan,
            seed.Baseline == null ? null : FormatCycles(seed.Baseline.Lifespan));

        SetComparedValue(WaterConsumptionLabel, seed.WaterConsumption.ToString("0.##"), seed.WaterConsumption, seed.Baseline?.WaterConsumption);
        SetComparedValue(NutrientConsumptionLabel, seed.NutrientConsumption.ToString("0.##"), seed.NutrientConsumption, seed.Baseline?.NutrientConsumption);
        SetComparedRange(TemperatureLabel,
            $"{seed.MinimumTemperature:0.##}-{seed.MaximumTemperature:0.##} K",
            seed.MinimumTemperature,
            seed.MaximumTemperature,
            seed.Baseline == null
                ? null
                : $"{seed.Baseline.MinimumTemperature:0.##}-{seed.Baseline.MaximumTemperature:0.##} K",
            seed.Baseline?.MinimumTemperature,
            seed.Baseline?.MaximumTemperature);
        SetComparedRange(PressureLabel,
            $"{seed.MinimumPressure:0.##}-{seed.MaximumPressure:0.##} kPa",
            seed.MinimumPressure,
            seed.MaximumPressure,
            seed.Baseline == null
                ? null
                : $"{seed.Baseline.MinimumPressure:0.##}-{seed.Baseline.MaximumPressure:0.##} kPa",
            seed.Baseline?.MinimumPressure,
            seed.Baseline?.MaximumPressure);
        SetComparedValue(ToxinToleranceLabel, seed.ToxinTolerance.ToString("0.##"), seed.ToxinTolerance, seed.Baseline?.ToxinTolerance);
        SetComparedValue(PestToleranceLabel, seed.PestTolerance.ToString("0.##"), seed.PestTolerance, seed.Baseline?.PestTolerance);
        SetComparedValue(WeedToleranceLabel, seed.WeedTolerance.ToString("0.##"), seed.WeedTolerance, seed.Baseline?.WeedTolerance);

        SetBoolean(ViableLabel, seed.Viable, seed.Baseline?.Viable);
        SetBoolean(SeedlessLabel, seed.Seedless, seed.Baseline?.Seedless);
        SetBoolean(LigneousLabel, seed.Ligneous, seed.Baseline?.Ligneous);
        SetComparedText(HarvestTypeLabel,
            FormatHarvestType(seed.HarvestType),
            seed.Baseline == null ? null : FormatHarvestType(seed.Baseline.HarvestType),
            seed.Baseline != null && seed.HarvestType != seed.Baseline.HarvestType);

        EstimatedYieldLabel.Text = seed.Products.Count == 0
            ? Loc.GetString("seed-analyzer-no-products")
            : Loc.GetString("seed-analyzer-estimated-yield", ("yield", Math.Max(1, seed.Yield)));
        FillProducts(seed.Products);
        FillReagents(seed.Reagents);
        FillGases(ConsumedGasesContainer, seed.ConsumedGases);
        FillGases(ProducedGasesContainer, seed.ProducedGases);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdatePrintButton();
    }

    private void UpdatePrintButton()
    {
        PrintButton.Disabled = !_hasSeed || _timing.CurTime < _printReadyAt;
    }

    private void FillProducts(List<SeedAnalyzerProductData> products)
    {
        ProductsContainer.RemoveAllChildren();
        if (products.Count == 0)
        {
            AddLine(ProductsContainer, Loc.GetString("seed-analyzer-no-products"), NeutralColor);
            return;
        }

        foreach (var product in products)
        {
            var name = _prototypes.TryIndex<EntityPrototype>(product.PrototypeId, out var prototype)
                ? Loc.GetString(prototype.Name)
                : product.PrototypeId;
            AddLine(ProductsContainer, Loc.GetString("seed-analyzer-product-line", ("name", name)), GoodColor);
        }
    }

    private void FillReagents(List<SeedAnalyzerReagentData> reagents)
    {
        ReagentsContainer.RemoveAllChildren();
        if (reagents.Count == 0)
        {
            AddLine(ReagentsContainer, Loc.GetString("seed-analyzer-no-reagent"), NeutralColor);
            return;
        }

        foreach (var reagent in reagents)
        {
            var name = _prototypes.TryIndex<ReagentPrototype>(reagent.ReagentId, out var prototype)
                ? prototype.LocalizedName
                : reagent.ReagentId;
            AddLine(ReagentsContainer, Loc.GetString("seed-analyzer-reagent-line", ("name", name),
                    ("current", reagent.CurrentAmount), ("min", reagent.MinimumAmount), ("max", reagent.MaximumAmount)),
                GoodColor);
        }
    }

    private void FillGases(BoxContainer container, List<SeedAnalyzerGasData> gases)
    {
        container.RemoveAllChildren();
        if (gases.Count == 0)
        {
            AddLine(container, Loc.GetString("seed-analyzer-none"), NeutralColor);
            return;
        }

        foreach (var gas in gases)
        {
            var name = _prototypes.TryIndex<GasPrototype>(gas.GasId, out var prototype)
                ? Loc.GetString(prototype.Name)
                : gas.GasId;
            AddLine(container, Loc.GetString("seed-analyzer-gas-line", ("name", name), ("amount", gas.Amount)),
                container == ProducedGasesContainer ? GoodColor : NeutralColor);
        }
    }

    private static void AddLine(BoxContainer container, string text, Color color)
    {
        BotanyAnalyzerUiHelpers.AddRichLine(container, text, color);
    }

    private static void SetComparedValue(RichTextLabel label,
        string text,
        float value,
        float? baseline,
        string? baselineText = null)
    {
        SetComparedText(label,
            text,
            baselineText ?? baseline?.ToString("0.##"),
            baseline != null && !MathHelper.CloseTo(value, baseline.Value));
    }

    private static void SetComparedRange(RichTextLabel label,
        string text,
        float minimum,
        float maximum,
        string? baselineText,
        float? baselineMinimum,
        float? baselineMaximum)
    {
        var changed = baselineMinimum != null && baselineMaximum != null &&
            (!MathHelper.CloseTo(minimum, baselineMinimum.Value) ||
             !MathHelper.CloseTo(maximum, baselineMaximum.Value));
        SetComparedText(label, text, baselineText, changed);
    }

    private static void SetBoolean(RichTextLabel label, bool value, bool? baseline)
    {
        SetComparedText(label,
            FormatBoolean(value),
            baseline == null ? null : FormatBoolean(baseline.Value),
            baseline != null && value != baseline.Value);
    }

    private static void SetComparedText(RichTextLabel label, string text, string? baseline, bool changed)
    {
        var currentColor = changed ? GoodColor : NeutralColor;
        var message = new FormattedMessage();
        message.PushColor(currentColor);
        message.AddText(text);
        message.Pop();

        if (baseline != null)
        {
            message.AddText(" ");
            message.AddMarkupOrThrow($"[font size=10][color=#8F8F8F]({FormattedMessage.EscapeText(baseline)})[/color][/font]");
        }

        label.SetMessage(message);
    }

    private static string FormatBoolean(bool value) =>
        Loc.GetString(value ? "seed-analyzer-yes" : "seed-analyzer-no");

    private static string FormatHarvestType(SeedAnalyzerHarvestType harvestType)
    {
        return harvestType switch
        {
            SeedAnalyzerHarvestType.Repeat => Loc.GetString("seed-analyzer-harvest-repeat"),
            SeedAnalyzerHarvestType.SelfHarvest => Loc.GetString("seed-analyzer-harvest-automatic"),
            _ => Loc.GetString("seed-analyzer-harvest-single")
        };
    }

    private static string FormatCycles(float value) =>
        Loc.GetString("seed-analyzer-cycles", ("value", value.ToString("0.##")));
}
